packages:
  - apps/*
  - packages/*
  - tools/*
catalog:
  prettier: ^3.5.3
  typescript: ^5.8.3
  turbo: ^2.5.0
  '@eslint/js': ^9.24.0
  '@types/eslint-config-prettier': ^6.11.3
  eslint: ^9.24.0
  eslint-config-prettier: ^10.1.1
  eslint-config-turbo: ^2.5.0
  eslint-plugin-import: ^2.31.0
  eslint-plugin-only-warn: ^1.1.0
  eslint-plugin-turbo: ^2.5.0
  eslint-plugin-vue: ^10.0.0
  globals: ^16.0.0
  typescript-eslint: ^8.29.0
  tailwind-merge: ^3.1.0
  tailwindcss: ^4.1.3
  tailwindcss-animate: ^1.0.7
  '@tailwindcss/vite': ^4.1.3
  vite: ^6.2.5
  reka-ui: ^2.2.0
  lucide-vue-next: ^0.487.0
  clsx: ^2.1.1
  '@types/node': ^22.14.0
  zod: ^3.24.2
  dotenv-cli: ^8.0.0
  unbuild: ^3.5.0
  '@fastify/oauth2': ^8.1.2
  fastify: ^5.2.2
  '@fastify/cors': ^11.0.1
  '@fastify/swagger': ^9.4.2
  '@fastify/swagger-ui': ^5.2.2
  fastify-type-provider-zod: ^4.0.2
  '@fastify/cookie': ^11.0.2
  '@fastify/env': ^5.0.2
  '@fastify/session': ^11.1.0
  pino-pretty: ^7.0.0
  zod-to-json-schema: ^3.24.5
  ofetch: ^1.4.1
  pinia: ^3.0.1
  '@tanstack/vue-query': ^5.72.0
  '@tanstack/vue-query-devtools': ^5.72.0
  '@kitbag/router': ^0.20.0
  vue-router: '4.5.0'

onlyBuiltDependencies:
  - esbuild
